### PR TITLE
OM - Fix Table in Governance (Catena-X Data Space Clearance List)

### PR DESCRIPTION
**Pull request by werner-roman**
image

### CODE REVIEW

**Comment by jSchuetz88** [comment]
@werner-roman Is that already fixed? For me it seems to work fine in the current version?

**Comment by werner-roman** [comment]
@jSchuetz88 https://catenax-ev.github.io/docs/next/operating-model/how-data-space-governance#implementation-and-set-up

This is the view i have under the link:
image

**Comment by jSchuetz88** [comment]
> @jSchuetz88 https://catenax-ev.github.io/docs/next/operating-model/how-data-space-governance#implementation-and-set-up
> 
> This is the view i have under the link: image

@werner-roman Ah, my bad. But your change updates the wrong table?

**Comment by werner-roman** [comment]
@jSchuetz88  updated the PR ^^

**Review by jSchuetz88 — APPROVED** [review]
Sorry, worked with the wrong branch. Looks good!

**Pull request merged**
