### PR TITLE
 Add category "certification" and 24.03 Input

### PR DESCRIPTION
**Pull request by werner-roman**
- Add "Certification" as a new category
- rework the nav-bar
- add input for 24.03 as from the current Catena-X Website.
- Content is coming from: https://github.com/catenax-eV/cx-certification

### CODE REVIEW

**Comment by werner-roman** [comment]
@AnnKaCatX  FYI 👍

**Review by stephanbcbauer — APPROVED** [review]
LGTM -> it was not a change in your PR, but does the wording “Releases Notes” exist? Isn't it just Release Notes?

Since the menu already says Releases, does it make sense to have an entry Releases Notes? It looks little bit akward :)

Related to certification, so the action for syncing can be implemented?

**Comment by stephanbcbauer** [comment]
> LGTM -> it was not a change in your PR, but does the wording “Releases Notes” exist? Isn't it just Release Notes?
> 
> Since the menu already says Releases, does it make sense to have an entry Releases Notes? It looks little bit akward :)
> 
> Related to certification, so the action for syncing can be implemented?

@werner-roman you are always looking for quality... 

image

At least a reply to my comment would have been desirable ;)

**Comment by werner-roman** [comment]
Hey @stephanbcbauer ,

sry - went under :(
Yes it typo - fix here: https://github.com/catenax-eV/catenax-ev.github.io/pull/133

Regarding the Naming generally: I am TBH not sure whats best. I think we need a "title" for the Sub-Pages:
- Release Notes
- Release Management
- Timelines

Should we name it "Release Timelines" for consistency or vise-versa:

Releases:
- Notes
- Management
- Timelines

The Sync would be ready now -> we are working on the certification - we would give you a ping to start the Sync 👍

**Pull request merged**
