### PR TITLE
# adapted the links in the Operating Model to link from "jupiter" to "Jupiter"

### PR DESCRIPTION
**Pull request by werner-roman**
Hardcoded links have contained "next" in the Jupiter release which links them to "latest / preview" even though they should link to "Jupiter"

### CODE REVIEW

**Review by stephanbcbauer — COMMENTED** [review]
LGTM, but ... right now, the links are referencing the current “current” (no next in the link and also no dedicated “release name” ... but what happens if we execute the Plug-in Again? These links would still link to current, which is in our case than IO?

I see a problem here? :)

**Comment by stephanbcbauer** [comment]
> LGTM, but ... right now, the links are referencing the current “current” (no next in the link and also no dedicated “release name” ... but what happens if we execute the Plug-in Again? These links would still link to current, which is in our case than IO?
> 
> I see a problem here? :)

And i think here is the solution… the links should be always relative (https://docusaurus.io/docs/versioning#link-docs-by-file-paths) because than it is always linked in the correct folder versioned or next.

The versioning plug-in doesn't change something in the md files, it creates the links during build time directly in html.

So i think in your case, the link shouldn't be
```
// old

https://catenax-ev.github.io/docs/next/certification/certification
```

and it also should not be
```
// new (suggestion in this PR)
https://catenax-ev.github.io/docs/certification/certification
```

but, it should be
```
../../certification/certification
```

or what is maybe better related the docs -> **Just tested it ... It only works with THIS**

```

../../certification/certification/certification.md
```

**Comment by werner-roman** [comment]
Hey @stephanbcbauer,

I 100% agree this would be great.

The problem comes from our internal workflow for all repos delivered in the library.

e.g. in the [OM Repo](https://github.com/catenax-eV/cx-operating-model) I see two options:
1. We use the approach mentioned: `
../../certification/certification/certification.md`
- Hard to create in OM as those files don't exist in the repo
- Broken link checker will always fail

2. We use `HTTP://....`:
- we have the problem we are running in now.

I think we need to find a ways which mitigates both issues:
- working in the "chapter repos" -> OM, WM, ...
- proper automatic versioning in Docusaurus

**Comment by werner-roman** [comment]
changes made in: https://github.com/catenax-eV/catenax-ev.github.io/pull/142

Long-Term solution open

**Pull request closed without merging**
