### PR TITLE
Update from Working-model: fe2076b

### PR DESCRIPTION
**Pull request by jSchuetz88**
This PR updates the branch with the latest changes from Working-model. Commit ID: fe2076b

### CODE REVIEW

**Comment by stephanbcbauer** [comment]
@jSchuetz88 can you resolve the conflicts? I am not sure which content is the correct one :)

**Comment by jSchuetz88** [comment]
> @jSchuetz88 can you resolve the conflicts? I am not sure which content is the correct one :)

Unfortunately, I have the same problem.
@Grand-Thibault could you check?

**Comment by Grand-Thibault** [comment]
@jSchuetz88 done

**Review by Grand-Thibault — APPROVED** [review]
lgtm

**Pull request merged**
