### PR TITLE
Add (governance framework)

### PR DESCRIPTION
**Pull request by jSchuetz88**
* Added all contents of the Governance Framework for Data Space Operations (for R24.03 and next)
* Updated the top-navigation

Bildschirmfoto 2024-06-19 um 22 04 39

### CODE REVIEW

**Review by stephanbcbauer — CHANGES_REQUESTED** [review]
We should avoid . and , in the names. This needs to be changed. SOrry

**Comment by werner-roman** [comment]
@jSchuetz88 
-> Operating model wieder ein eigener punkt in der Menüleiste

-> "Governance Model" umbenennen in "regulatory framework"

**Comment by jSchuetz88** [comment]
Done 
Bildschirmfoto 2024-06-20 um 12 53 53

**Review by werner-roman — APPROVED** [review]
looks good +1

**Review by stephanbcbauer — APPROVED** [review]
LGTM now

**Pull request merged**
